### ISSUE TITLE
Feature : Set plugin search path (esp for MSVC)

### ISSUE THREAD

**Issue by elliotwoods** [quixdb/squash#187]
Apologies if these types of questions are better referred to a forum.

Where can plugins be located?
(especially on windows)

I'm reading:
```c++
    plugin_file_name = squash_strdup_printf ("%s/%ssquash%s-plugin-%s%s", plugin->directory, SQUASH_SHARED_LIBRARY_PREFIX, SQUASH_VERSION_API, plugin->name, SQUASH_SHARED_LIBRARY_SUFFIX);
```
from plugin.c

And in config.h:
```c++
#define SQUASH_INSTALL_PREFIX "C:/Program Files/squash"
#define SQUASH_PLUGIN_DIR "C:/Program Files/squash/lib/squash/0.8/plugins"
#define SQUASH_SEARCH_PATH "C:/Program Files/squash/lib/squash/0.8/plugins"
#define SQUASH_SHARED_LIBRARY_PREFIX ""
#define SQUASH_SHARED_LIBRARY_SUFFIX ".dll"
#define SQUASH_BUILD_TYPE ""
```
(side question : is this config.h written by c-make?)

I'm finding that the Install script (which halted when it got to `density`) put the dll's into that `SQUASH_PLUGIN_DIR` with the correct hierarchy structure. So those plugins appear by default.

Q1) Does squash search for plugins at this location only (i.e. not locally)?

Q2) Can the user specify a search path for plugins?

I can see:
```c++
SquashPlugin*
squash_plugin_new (char* name, char* directory, SquashContext* context) {
  SquashPlugin* plugin = (SquashPlugin*) squash_malloc (sizeof (SquashPlugin));
```
in plugin.c

and

```c++
squash_context_add_plugin (SquashContext* context, char* name, char* directory) {
```
in context.c (which calls `squash_plugin_new`)

These functions are not exposed in the headers.

Q3) Is there a good way to publicly operate this functions?

I've tried manually copying plugins into this folder:
When I call `squash_foreach_codec` I get
* brieflz
* brotli
* bsc
* bzip2
* copy
* crush
* density (not valid)

These plugins (except density) were copied by the INSTALL project to the `Program Files` location. However density dll is missing, and if I add another plugin manually:

![image](https://cloud.githubusercontent.com/assets/328294/12878074/7efa070e-ce61-11e5-99e0-1f5197f11c3a.png)

Then it is not shown in the list.

Q4) Is this plugin list configured somewhere? (rather than searching the directory)

Ideally I want to be able to keep my squash and plugin dll's next to my application
(to make the application portable, but also to make the development environment portable)
Ideally something like this:
![image](https://cloud.githubusercontent.com/assets/328294/12878019/3dcd77a8-ce60-11e5-9575-694bf6389b0b.png)
(or perhaps in a subdir `plugins/squash`)

Thank you

**Comment by nemequ** [comment]
> Apologies if these types of questions are better referred to a forum.

That's probably a good idea.  See http://quixdb.github.io/squash/#support.  The mailing list (which doubles as a forum) is probably the most appropriate place for this discussion.  The issue tracker is more for, well, issues.  I guess if you phrased it as "Document plugin locations on Windows", which I'll change the title to.

> Where can plugins be located?
> (especially on windows)

First, a `SQUASH_PLUGINS` environment variable is checked.  If the variable is set (`getenv(SQUASH_PLUGINS) != NULL`), that path will be used as the search path.

If the `SQUASH_PLUGINS` environment variable is not set, it will use the `SQUASH_SEARCH_PATH` value defined by CMake and written to `config.h` (which, to be clear, is a *private* header, and will not be installed).  The default value for this is the same as the directory CMake install the plugins to, which is `${CMAKE_INSTALL_FULL_LIBDIR}/squash/${SQUASH_VERSION_API}/plugins`, but you can override it at configure time (`cmake -DSEARCH_PATH="whatever"`).

On Windows the search path is is a semi-colon separated list of directories.  On other operating systems it is a colon-separated list.  Other than that, the only real difference between Windows and other operating systems is that other operating systems have a standard location we can install plugins to, so everything just works.  On Windows you pretty much have to set the search path yourself, either at compile time or run time.

When searching for plugins, Squash will look for `$current_search_path/*/squash.ini` to detect if a plugin is present.  If so, it will parse the ini, but will *not* load the DLL.

> These functions are not exposed in the headers.
> 
> Q3) Is there a good way to publicly operate this functions?

No.  In the future I might consider an API to set the search path, but TBH I don't see a reason not to just use `setenv` (or, on Windows, `putenv_s`) to set the `SQUASH_PLUGINS` environment variable.  I'm not going to say I'll never expose the `squash_plugin_new` or `squash_context_add_plugin`, but it would require a very compelling use case that I haven't thought of.

> Q4) Is this plugin list configured somewhere? (rather than searching the directory)

Nope, there is no hardcoded list.  You can add and remove plugins at will.  Otherwise it would be impossible for third parties to distribute plugins.  The plugin enumeration code probably bails if it fails to load a plugin; I'll look into fixing that.  Unfortunately, as plugins are loaded on-demand, if a squash.ini exists for a plugin but the DLL doesn't work for any reason (like, say, the DLL being missing) we won't know about it until you actually try to do something with the plugin.

> Ideally I want to be able to keep my squash and plugin dll's next to my application
> (to make the application portable, but also to make the development environment portable)
> Ideally something like this:

The INI files are definitely necessary, so the structure proposed in your screenshot definitely will not work.  The currently supported way to do this would be to create a folder for each plugin, and have the DLL and INI files for the plugin in that folder.  Something like:

* data/
* assimp.dll
* fmodex.dll
* …
* squash0.8.dll
* squash-plugins/
* squash-plugins/brieflz/
* squash-plugins/brieflz/squash.ini
* squash-plugins/brieflz/squash0.8-plugin-brieflz.dll
* …

Then use the SQUASH_PLUGINS environment variable to set the search path to `$path_to_your_dir/squash`

Technically you don't really need the "squash-plugins/" directory; you could set the search path to just `$path_to_your_dir`, but that seems rather ugly to me.  You could also call it something other than "squash-plugins", but inside of that directory the file structure needs to be pretty strict.

> (or perhaps in a subdir plugins/squash)

Yep, `plugins/squash` would work, too.

**Comment by nemequ** [comment]
> I've tried manually copying plugins into this folder:
> When I call squash_foreach_codec I get

I don't suppose you could share the source code for this?  When I remove the density shared library here it's handled pretty well here…

**Comment by elliotwoods** [comment]
From https://social.msdn.microsoft.com/Forums/vstudio/en-US/e115ed93-f9eb-49ba-a1db-b3f4ee02bd93/application-ignores-env-variables-setting?forum=vcgeneral

> So if your application then calls putenv then it will actually call putenv in msvcr100.dll not msvcrt.dll. This actually turns out to be a problem because dynamic versions of the CRT don't share data between versions, so while all modules using msvcr100.dll would share data, such as environment variables, these are not shared between the modules using msvcr100.dll and msvcrt.dll.

Since squash is a dll, it uses whichever MSVCR runtime it happened to be built with. So `_putenv_s`, etc won't work if your application is using a different runtime (e.g. debug runtime). Possible workarounds:

* Use a seperate squash dll for debug mode
* Have a squash_set_plugin_dir() function  (this sounds the best!)
* Have a squash_put_env_var or similar which allows you to set environment variables 'through' the squash dll, to ensure that the environment variables are being set in the right context for squash to listen to them

**Comment by elliotwoods** [comment]
Here's a hack attempt at this:
https://github.com/elliotwoods/squash/commit/17e210ba6a945d39cfa530c35f59b6cfae577020

**Comment by jibsen** [comment]
> Since squash is a dll, it uses whichever MSVCR runtime it happened to be built with. So _putenv_s, etc won't work if your application is using a different runtime (e.g. debug runtime).

That is just awful. I found an article with a deeper explanation [here](http://siomsystems.com/mixing-visual-studio-versions/), which suggest providing your own wrappers for `getenv()` and `putenv()` to work around this issue.

Back when we were using glib for testing we had an issue with crashes on Windows when closing file handles, which was the same issue.

**Comment by nemequ** [comment]
Okay, this should be sorted now, thanks for the help.  I had no idea Windows would mix runtimes in a single executable.

> Here's a hack attempt at this:
> elliotwoods@17e210b

Thanks :).  I ended up doing something pretty similar.

I didn't like the idea of overriding the `SQUASH_PLUGINS` environment variable; I think `SQUASH_PLUGINS` should have priority, so my patch adds another layer in between the compile-time default and the environment variable.

> That is just awful.

Agreed.

> I found an article with a deeper explanation here, which suggest providing your own wrappers for getenv() and putenv() to work around this issue.

Thanks for that; interesting (/horrifying) reading.  I guess we should add some warnings to the `squash_file_steal` and `squash_file_free` functions…

**Comment by elliotwoods** [comment]
thank you! i'll move over to the new code right away
